### ISSUE TITLE
Default for script questions?

### ISSUE THREAD

**Issue by arigoldx** [riveramj/liftweb-generator#11]
When I saw

> Path does not exist, create directory? [Y/n]:

I pressed return, thinking that the `Y` was capitalized to show that it was default.. am I off on that? I think that's often the case in Unix shell scripts but I might be wrong.

**Comment by riveramj** [comment]
ah fair point. changing

**Comment by riveramj** [comment]
fixed in https://github.com/riveramj/lift-generator/commit/8a82ea599a774940cbd46c838b6695f7bac0f612
