### ISSUE TITLE
potential error in build.scala

### ISSUE THREAD

**Issue by arigoldx** [riveramj/liftweb-generator#12]
For shits and giggles I tried running `sbt` as soon as I was finished generating the project and got this:

```
~/src/website  $ sbt
[info] Loading global plugins from /Users/arigold/.sbt/0.13/plugins
[info] Updating {file:/Users/arigold/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/arigold/src/website/project
[info] Updating {file:/Users/arigold/src/website/project/}website-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/arigold/src/website/project/target/scala-2.10/sbt-0.13/classes...
[error] /Users/arigold/src/website/project/build.scala:29: type mismatch;
[error]  found   : Seq[sbt.Setting[_]]
[error]  required: sbt.Def.Setting[_]
[error]     WebPlugin.webSettings
[error]               ^
[error] one error found
[error] (compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Dunno if this makes sense given that I haven't edited or created _anything_ but that `type mismatch` makes me wonder if it ain't something.

**Comment by riveramj** [comment]
> /Users/arigold/src/website/project/target/scala-2.10/sbt-0.13/classes

So i was able to reproduce some issues but thats cause i used `scala 2.10`. did you choose that or did you use the default 2.11 and it still used 2.10?

It would seem that my versions arent safe with older versions of scala but i dont think ppl would be using 2.10 much. if they are you'd have to switch things up a bit.

Maybe i could add a message to that effect...

**Comment by arigoldx** [comment]
Yah, I've got `scalaVersion := "2.11.4"` 'cause that's what's on my machine. Figured I'd use the same for work as for home...tho maybe I can upgrade to `2.11.7` 'cause I feel like the minor version can't break that much (and I'm guessing I can downgrade if necessary).

That said, due to

> [info] Compiling 1 Scala source to /Users/arigold/src/website/project/target/scala-2.10/sbt-0.13/classes...

it seems like it's using `2.10` tho I told it not to. `scalaVersion := "2.11.4"` is in my `build.scala`, scouts honor.

**Comment by riveramj** [comment]
out of curiosity try the the `build.sbt` file. Does that still show the error? and is it still `2.10` or `2.11`?

**Comment by arigoldx** [comment]
yep! `build.sbt` worked like a charm. in that `sbt` starts up with no error.

so in `build.sbt` I have `scalaVersion := "2.11.7"`

if I do a `scala -version` I get:

```
~/src  $ scala -version
Scala code runner version 2.11.4 -- Copyright 2002-2013, LAMP/EPFL
```

and, within

```
> scalaVersion
[info] 2.11.7
```

**Comment by riveramj** [comment]
it really seems like something local but i'm not 100% sure. I'll continue to think on it

**Comment by riveramj** [comment]
@arigoldx honestly i dont know much more of what this could be. have you had any success in chasing it down?

**Comment by arigoldx** [comment]
nope. I realize that since it's a `build.scala` problem and not a `build.sbt` problem that understanding how `sbt` reads `build.scala` will help but I'ma leave that for ~~a rainy day~~ some free time.

**Comment by arigoldx** [comment]
if I find something out I'll post.. until then, let's close this puppy.
