### ISSUE TITLE
Lookup newest scala & lift versions

### ISSUE THREAD

**Issue by riveramj** [riveramj/liftweb-generator#14]
It would be ideal if the generator tried to lookup the newest scala & lift versions of the current major version. This would allow it to keep up to date with minor releases w/o manual intervention.

This would prevent pushing versions that may include security vulnerabilities that have been patched already.

This should all be possible by looking up the versions on maven.

**Comment by arigoldx** [comment]
And maybe also look up the user's current scala/lift version to make sure things jive?

**Comment by riveramj** [comment]
> And maybe also look up the user's current scala/lift version to make sure things jive?

huh? I mean we'll look up from maven and populate. its by project so it'll just download if the user doesnt have it

**Comment by arigoldx** [comment]
Ahh.. didn't know it's by project. That you could have different scala and lift versions by project.

'gotta learn more about `~/.ivy2` and all that..
